using UnityEngine;
using System.Collections.Generic;

/* Written by Timofey Peshin (timoffex)
 * */
public class PowerupZone : MonoBehaviour {

	/// <summary>
	/// The list of powerups that can be generated by this zone.
	/// </summary>
	public List<GameObject> allowedPowerups;

	// Use this for initialization
	void Start () {

		// Replace self with a random powerup from the allowedPowerups list.
		Generate ();
	}

	/// <summary>
	/// Places a random powerup at the location of this powerup zone and deletes self.
	/// </summary>
	public void Generate () {


		if (allowedPowerups.Count > 0) {
			GameObject randomPowerupPrefab = allowedPowerups [Random.Range (0, allowedPowerups.Count)];

			Instantiate (randomPowerupPrefab, transform.position, Quaternion.identity);
		}


		Destroy (gameObject);
	}

}

